name: R-benchmark

# The condition of toggling this workflow. For this workflow, it will be toggled when push or pull request happens at master branch.
on:
  push:
    branches: [ master ]
    paths-ignore: # the ignored path for toggling.
      - '.github/workflows/**' # Changes in workflow files will not toggle this action
      - 'Rperform_Data/**' # Changes in result data will not toggle this action
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - '.github/workflows/**'
      - 'Rperform_Data/**'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Checkout@v2 is a Github official workflow that can checkout your repo on VM.
    - name: r-benchmark
      uses: LooDaHu/R-benchmark@v1
      with:
        username: LooDaHu # Replace it with your Github username.
# A timing result of current pushed commit will be added into the result dataset once changes happen at non-ignored directories. 
